name: Go Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: action/checkout@v2

    - name: Set up Go
      uses: action/setup-go@v2
      with:
        go-version: '1.21'

    - name: go test ./...