name: Go Test

on: 
  push:
    branches: 
      - main

jobs:
  go_test:
    runs-on: [ubuntu-latest]

    steps:
    - name: go 
      uses: actions/setup-go@v5.0.1

    - name: Set up Go
      uses: action/setup-go@v2
      with:
        go-version: '1.21'

    - name: go test ./...
  

          
